## Using Tensorflow

In [1]:
import os
import tensorflow as tf

2023-03-10 18:40:43.219823: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-03-10 18:40:43.219876: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
data_dir = "../data/images/orthologs_hemoglobin_beta/full"

In [16]:

images = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    label_mode=None,
    batch_size = 4,
    image_size=(441, 441)
)

for img in images:
    result = tf.image.ssim(img, img, max_val=255, filter_size=3,
                          filter_sigma=0.3, k1=0.01, k2=0.03)
    print(
        result.numpy()
    )


Found 15 files belonging to 1 classes.
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1.]


In [23]:
tf.math.reduce_max(result).numpy()

1.0

In [92]:
imgs=[]
for f in os.listdir(data_dir):
    img = tf.expand_dims(
        tf.image.decode_image(
            tf.io.read_file(
                os.path.join(
                    data_dir, f)), channels=3), axis=0)
    imgs.append(img)
imgs = tf.concat(imgs, axis=0)

In [93]:
imgs.shape

TensorShape([15, 441, 441, 3])

In [43]:
im1 = tf.expand_dims(im1, axis=0)
im2 = tf.expand_dims(im2, axis=0)

In [48]:
result = tf.image.ssim(im1, im2, max_val=255, filter_size=11,
                          filter_sigma=1.5, k1=0.01, k2=0.03)[0]

In [57]:
result.numpy()

0.41484135

In [58]:
tf.image.ssim_multiscale(im1, im2, max_val=255, filter_size=11,
                          filter_sigma=1.5, k1=0.01, k2=0.03)[0].numpy()

0.7579008

In [56]:
tf.concat([im1, im2], 0)

<tf.Tensor: shape=(2, 3000, 3000, 4), dtype=uint8, numpy=
array([[[[255,   0,  12, 255],
         [  0,   0,   0, 255],
         [  0,  12,   0, 255],
         ...,
         [  0,   0,   0, 255],
         [  0,  12,   0, 255],
         [ 12,   0,  12, 255]],

        [[  0,   0,   0, 255],
         [255,   0,  12, 255],
         [  0,   0,   0, 255],
         ...,
         [ 38,   0,  12, 255],
         [  0,   0,   0, 255],
         [  0,   0,   0, 255]],

        [[  0,  12,   0, 255],
         [  0,   0,   0, 255],
         [255,   0,  12, 255],
         ...,
         [  0,   0,   0, 255],
         [ 38,   0,  12, 255],
         [  0,  25,   0, 255]],

        ...,

        [[  0,   0,   0, 255],
         [ 38,   0,  12, 255],
         [  0,   0,   0, 255],
         ...,
         [255,   0,  12, 255],
         [  0,   0,   0, 255],
         [  0,   0,   0, 255]],

        [[  0,  12,   0, 255],
         [  0,   0,   0, 255],
         [ 38,   0,  12, 255],
         ...,
         [  0

In [59]:
for img in os.listdir(data_dir):
    print(
        f"A0 x {img.split('.')[0]}: ",
        tf.image.ssim(
            tf.expand_dims(tf.image.decode_image(tf.io.read_file(os.path.join(data_dir, "A0.png"))), axis=0),
            tf.expand_dims(tf.image.decode_image(tf.io.read_file(os.path.join(data_dir, img))), axis=0),
            max_val=255, filter_size=11,
            filter_sigma=1.5, k1=0.01, k2=0.03
           )[0].numpy()
    )

A0 x A0:  1.0
A0 x A1:  0.41484135
A0 x A2:  0.41419423
A0 x A3:  0.41434056
A0 x A4:  0.4149395
A0 x A5:  0.41466367
A0 x A6:  0.41470513
A0 x A7:  0.41471153
A0 x A8:  0.41526267
A0 x A9:  0.41501674
A0 x B0:  0.50130683
A0 x B1:  0.41474065
A0 x B2:  0.41426712
A0 x B3:  0.4150629
A0 x B4:  0.4147867
A0 x B5:  0.41471872
A0 x B6:  0.41454905
A0 x B7:  0.41443413
A0 x B8:  0.41449893
A0 x B9:  0.41479275
A0 x C0:  0.4399907
A0 x C1:  0.41444296
A0 x C2:  0.41507447
A0 x C3:  0.41512513
A0 x C4:  0.41448516
A0 x C5:  0.41442174
A0 x C6:  0.4146407
A0 x C7:  0.41490006
A0 x C8:  0.41429645
A0 x C9:  0.4150262
A0 x D0:  0.4341429
A0 x D1:  0.4148976
A0 x D2:  0.4142444
A0 x D3:  0.4144265
A0 x D4:  0.41463375
A0 x D5:  0.41498083
A0 x D6:  0.41462064
A0 x D7:  0.41440085
A0 x D8:  0.41492236
A0 x D9:  0.41458866


In [2]:
import pandas

In [8]:
indexes = [img.split('.')[0] for img in os.listdir(data_dir)]

In [11]:
df = pandas.DataFrame(index=indexes, columns=indexes)

In [12]:
df.loc[indexes[0], indexes[0]]

nan

In [13]:
for img1 in os.listdir(data_dir):
    for img2 in os.listdir(data_dir):
        df.loc[img1.split('.')[0], img2.split('.')[0]] = tf.image.ssim_multiscale(
                tf.expand_dims(tf.image.decode_image(tf.io.read_file(os.path.join(data_dir, img1))), axis=0),
                tf.expand_dims(tf.image.decode_image(tf.io.read_file(os.path.join(data_dir, img2))), axis=0),
                max_val=255, filter_size=11,
                filter_sigma=1.5, k1=0.01, k2=0.03
               )[0].numpy()

2021-12-07 14:00:44.040424: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-07 14:00:44.040525: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-07 14:00:44.040543: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (LAPTOP-PEBVG10A): /proc/driver/nvidia/version does not exist
2021-12-07 14:00:44.050089: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/mnt/c/Users/Diogo/.virtualenvs/bioinfo2.0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_25623/2902284024.py", line 7, in <module>
    filter_sigma=1.5, k1=0.01, k2=0.03
  File "/mnt/c/Users/Diogo/.virtualenvs/bioinfo2.0/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/mnt/c/Users/Diogo/.virtualenvs/bioinfo2.0/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 1096, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/mnt/c/Users/Diogo/.virtualenvs/bioinfo2.0/lib/python3.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 4438, in ssim_multiscale
    k2=k2)
  File "/mnt/c/Users/Diogo/.virtualenvs/bioinfo2.0/lib/python3.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 4223, i

TypeError: object of type 'NoneType' has no len()